# Generated by Django 4.0.3 on 2022-03-25 13:54

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=200, populate_from='name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('discount', models.BooleanField(default=False)),
                ('sale', models.DecimalField(decimal_places=2, default=1, max_digits=3)),
                ('country', models.CharField(db_index=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('full_description', models.TextField(blank=True)),
                ('stock', models.PositiveIntegerField()),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='main.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.category')),
            ],
            options={
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_rating', to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_order', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Принято в обработку', 'Принято в обработку'), ('Упакован и отправлен', 'Упакован и отправлен'), ('Доставлен покупателю', 'Доставлен покупателю'), ('Ожидание поступления товара', 'Ожидание поступления товара'), ('Отменен', 'Отменен')], default='Принято в обработку', max_length=50, verbose_name='Статус заказа')),
                ('total', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Итого')),
                ('payment', models.CharField(choices=[('Наличные', 'Наличные при получении'), ('Оплата картой', 'Оплата картой')], max_length=50, verbose_name='Способ оплаты')),
                ('delivery', models.CharField(choices=[('Самовывоз', 'Самовывоз'), ('Курьер', 'Курьер'), ('Почта', 'Почта')], max_length=50, verbose_name='Способ доставки')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('adress', models.TextField(null=True, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=13, null=True, verbose_name='Телефон')),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
                ('products', models.ManyToManyField(to='main.product', verbose_name='Товар')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='product/%Y/%m/%d')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='main.product')),
            ],
        ),
    ]
