# Generated by Django 4.0.3 on 2022-03-02 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_rating', to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_order', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(choices=[('processing', 'Принято в обработку'), ('shipped', 'Упакован и отправлен'), ('delivered', 'Доставлен покупателю'), ('waiting', 'Ожидание поступления товара'), ('cancel', 'Отменен')], default=True, verbose_name='Статус заказа')),
                ('total', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Итого')),
                ('payment', models.CharField(choices=[('cash', 'Наличные при получении'), ('card', 'Оплата картой')], max_length=10, verbose_name='Способ оплаты')),
                ('delivery', models.CharField(choices=[('pickup', 'Самовывоз'), ('courier', 'Курьер'), ('mail', 'Почта')], max_length=10, verbose_name='Способ доставки')),
                ('comment', models.TextField(blank=True)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.profile', verbose_name='Покупатель')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='product/%Y/%m/%d')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='main.product')),
            ],
        ),
    ]
