# Generated by Django 4.0.3 on 2022-03-03 14:27

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_product_brand_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(max_length=200),
        ),
    ]
