# Generated by Django 4.0.3 on 2022-03-07 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='buyer',
        ),
    ]
