# Generated by Django 4.0.3 on 2022-03-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_order_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'Принято в обработку'), ('shipped', 'Упакован и отправлен'), ('delivered', 'Доставлен покупателю'), ('waiting', 'Ожидание поступления товара'), ('cancel', 'Отменен')], default='processing', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
