# Generated by Django 4.0.3 on 2022-03-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Принято в обработку', 'Принято в обработку'), ('Упакован и отправлен', 'Упакован и отправлен'), ('Доставлен покупателю', 'Доставлен покупателю'), ('Ожидание поступления товара', 'Ожидание поступления товара'), ('Отменен', 'Отменен')], default='processing', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
