# Generated by Django 4.0.3 on 2022-03-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('Самовывоз', 'Самовывоз'), ('Курьер', 'Курьер'), ('Почта', 'Почта')], max_length=50, verbose_name='Способ доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('Наличные', 'Наличные при получении'), ('Оплата картой', 'Оплата картой')], max_length=50, verbose_name='Способ оплаты'),
        ),
    ]
