# Generated by Django 4.0.3 on 2022-03-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='adress',
            field=models.TextField(null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=13, null=True, verbose_name='Телефон'),
        ),
    ]
