# Generated by Django 4.0.3 on 2022-03-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_order_adress_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='data_order',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
