# Generated by Django 4.0.3 on 2022-03-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Принято в обработку', 'Принято в обработку'), ('Упакован и отправлен', 'Упакован и отправлен'), ('Доставлен покупателю', 'Доставлен покупателю'), ('Ожидание поступления товара', 'Ожидание поступления товара'), ('Отменен', 'Отменен'), ('Доставлен покупателю  и получена оценка', 'Доставлен покупателю и получена оценка')], default='Принято в обработку', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
