# Generated by Django 4.0.3 on 2022-03-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
